export const all_employees = {
    "Employees" : [
        {
        "userId":"1",
        "dateAdded": "2023-12-14",
        "jobTitleName":"Developer",
        "firstName":"Romin",
        "lastName":"Irani",
        "preferredFullName":"Romin Irani",
        "employeeCode":"E1",
        "region":"CA",
        "age": 50,
        "country": "Netherlands",
        "phoneNumber":"408-1234567",
        "emailAddress":"romin.k.irani@gmail.com",
        "profileImg": "https://st3.depositphotos.com/1017228/18878/i/450/depositphotos_188781580-stock-photo-handsome-cheerful-young-man-standing.jpg"
        },
        {
        "userId":"2",
        "dateAdded": "2023-12-14",
        "jobTitleName":"Developer",
        "firstName":"Neil",
        "lastName":"Irani",
        "preferredFullName":"Neil Irani",
        "employeeCode":"E2",
        "region":"CA",
        "age": 50,
        "country": "Netherlands",
        "phoneNumber":"408-1111111",
        "emailAddress":"neilrirani@gmail.com",
        "profileImg": "https://images.ctfassets.net/hrltx12pl8hq/3Mz6t2p2yHYqZcIM0ic9E2/3b7037fe8871187415500fb9202608f7/Man-Stock-Photos.jpg"
        
        },
        {
        "userId":"3",
        "dateAdded": "2023-12-16",
        "jobTitleName":"Program director",
        "firstName":"Tom",
        "lastName":"Hanks",
        "preferredFullName":"Tom Hanks",
        "employeeCode":"E3",
        "region":"CA",
        "age": 61,
        "country": "Italy",
        "phoneNumber":"408-2222222",
        "emailAddress":"tomhanks@gmail.com",
        "profileImg": "https://media.istockphoto.com/id/1384672095/photo/outdoor-headshot-of-early-50s-multiracial-executive.jpg?s=612x612&w=0&k=20&c=0k4BglYgFiXxHywMtOhT2MR5okUQnOEGIeqJbti13dM="
        },
        {
        "userId":"4",
        "dateAdded": "2023-12-16",
        "jobTitleName":"Marketing specialist",
        "firstName":"Mark",
        "lastName":"de Vries",
        "preferredFullName":"Mark de Vries",
        "employeeCode":"E1",
        "region":"CA",
        "age": 59,
        "country": "Israel",
        "phoneNumber":"408-1234567",
        "emailAddress":"romin.k.irani@gmail.com",
        "profileImg": "https://media.istockphoto.com/id/1364917563/photo/businessman-smiling-with-arms-crossed-on-white-background.jpg?s=612x612&w=0&k=20&c=NtM9Wbs1DBiGaiowsxJY6wNCnLf0POa65rYEwnZymrM="
        },
        {
        "userId":"5",
        "dateAdded": "2023-12-18",
        "jobTitleName":"Developer",
        "firstName":"Paul",
        "lastName":"Smith",
        "preferredFullName":"Paul Smith",
        "employeeCode":"E1",
        "region":"CA",
        "age": 50,
        "country": "Israel",
        "phoneNumber":"408-1234567",
        "emailAddress":"paulsm@gmail.com",
        "profileImg": "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
        },
        {
        "userId":"6",
        "dateAdded": "2023-12-19",
        "jobTitleName":"Developer",
        "firstName":"Emma",
        "lastName":"Watts",
        "preferredFullName":"Emma Watts",
        "employeeCode":"E1",
        "region":"CA",
        "age": 12,
        "country": "Israel",
        "phoneNumber":"408-1234567",
        "emailAddress":"ew14554@gmail.com",
        "profileImg": "https://media.istockphoto.com/id/1386479313/photo/happy-millennial-afro-american-business-woman-posing-isolated-on-white.jpg?s=612x612&w=0&k=20&c=8ssXDNTp1XAPan8Bg6mJRwG7EXHshFO5o0v9SIj96nY="
        },
        {
        "userId":"7",
        "dateAdded": "2023-12-20",
        "jobTitleName":"Developer",
        "firstName":"Emma",
        "lastName":"Watts",
        "preferredFullName":"Emma Watts",
        "employeeCode":"E1",
        "region":"CA",
        "age": 50,
        "country": "Israel",
        "phoneNumber":"408-1234567",
        "emailAddress":"ew14554@gmail.com",
        "profileImg": "https://media.istockphoto.com/id/1386479313/photo/happy-millennial-afro-american-business-woman-posing-isolated-on-white.jpg?s=612x612&w=0&k=20&c=8ssXDNTp1XAPan8Bg6mJRwG7EXHshFO5o0v9SIj96nY="
        },
        {
        "userId":"8",
        "dateAdded": "2023-12-21",
        "jobTitleName":"UX Designer",
        "firstName":"Brenda",
        "lastName":"Watts",
        "preferredFullName":"Emma Watts",
        "employeeCode":"E1",
        "region":"CA",
        "age": 32,
        "country": "Israel",
        "phoneNumber":"408-1234567",
        "emailAddress":"ew14554@gmail.com",
        "profileImg": "https://media.istockphoto.com/id/1386479313/photo/happy-millennial-afro-american-business-woman-posing-isolated-on-white.jpg?s=612x612&w=0&k=20&c=8ssXDNTp1XAPan8Bg6mJRwG7EXHshFO5o0v9SIj96nY="
        }]
    }